apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: tinyllama-finetune-alpaca
spec:
  template:
    metadata:
      labels:
        app: llm-training
    spec:
      runtimeClassName: nvidia
      restartPolicy: Never
      containers:
      - name: trainer
        image: ghcr.io/navishashetty/llm-trainer:v1
        resources:
          limits:
            nvidia.com/gpu: 1
            memory: "16Gi"
            cpu: "4"
          requests:
            nvidia.com/gpu: 1
            memory: "8Gi"
            cpu: "2"
        volumeMounts:
        - name: models
          mountPath: /models
        env:
        - name: OUTPUT_DIR
          value: "/models/tinyllama-alpaca-finetuned"
      volumes:
      - name: models
        persistentVolumeClaim:
          claimName: models-pvc