apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-disks
  resources:
    requests:
      storage: 50Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: tinyllama-finetune-alpaca
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: llm-training
    spec:
      runtimeClassName: nvidia
      restartPolicy: Never
      containers:
      - name: trainer
        image: ghcr.io/navishashetty/llm-trainer:v1
        resources:
          limits:
            nvidia.com/gpu: 1
            memory: "16Gi"
            cpu: "4"
          requests:
            nvidia.com/gpu: 1
            memory: "8Gi"
            cpu: "2"
        volumeMounts:
        - name: models
          mountPath: /models
        env:
        - name: OUTPUT_DIR
          value: "/models/tinyllama-alpaca-finetuned"
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: huggingface-token
              key: token
        - name: HF_REPO
          value: "shettynavisha25/tinyllama-alpaca-finetuned"
        - name: TRANSFORMERS_CACHE
          value: "/models/.cache"
      volumes:
      - name: models
        persistentVolumeClaim:
          claimName: models-pvc